# Generated by Django 3.1.3 on 2022-12-29 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dislike',
            name='countDislikes',
            field=models.IntegerField(default=0),
        ),
    ]
