# Generated by Django 3.1.3 on 2022-12-29 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0002_auto_20221229_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='countLikes',
            field=models.IntegerField(default=0),
        ),
    ]
